//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Lab6
//  @ File Name : Application.java
//  @ Date : 2019-10-21
//  @ Author : AndrisBorbas

import java.io.FileNotFoundException;

public class Application {
	public static void main(String[] args) throws FileNotFoundException {
		PercentCounter pc = new PercentCounter();
		pc.register(new StdOutLogger());
		pc.register(new FileLogger("observer.txt"));
		pc.run();
	}
}