//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Lab6
//  @ File Name : Observer.java
//  @ Date : 2019-10-21
//  @ Author : AndrisBorbas

interface Observer {
	public void report(Observable observable);
}
