//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Lab6
//  @ File Name : StdOutLogger.java
//  @ Date : 2019-10-21
//  @ Author : AndrisBorbas

public class StdOutLogger implements Observer {

	@Override
	public void report(Observable observable) {
		System.out.println(observable);
	}
}
